[tool.poetry]
name = "split-xml-gyn"
version = "0.1.0"
description = ""
authors = ["ElderVivot <eldervivot@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
xmltodict = "^0.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
